name: Publish to GitHub Pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: "Publish"

    steps:
    - name: Install 'dokkoo' for Mokk compilation
      uses: actions-rs/install@v0.1
      with:
          crate: dokkoo
          use-tool-cache: true
    - name: Checkout Mokk
      uses: actions/checkout@v2
      with:
          path: ./mokk
    - name: "Checkout GitHub Pages environment"
      uses: actions/checkout@v2
      with:
          ref: gh-pages
          path: ./gh-pages
          token: ${{ secrets.PAT }}
    - name: Build
      run: |
          sudo apt-get -y install tree > /dev/null
          printf "Contents of Mokk:\n" && tree ./mokk
          find ./gh-pages -mindepth 1 ! -regex '^./gh-pages/.git\(/.*\)?' -delete
          cd ./mokk
          dokkoo build .
          cd ../
          cp -ar ./mokk/output/* ./gh-pages
          cp -ar ./mokk/assets ./gh-pages
          touch ./gh-pages/.nojekyll
          tee -a /gh-pages/.nojekyll > /dev/null <<EOT

          EOT
          printf "\nBuilt Mokk:\n" && tree ./gh-pages
    - name: Publish
      run: |
          cd ./gh-pages
          git config --global user.name 'Dokkoo'
          git config --global user.email 'MadeByEmil@users.noreply.github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -am "Publish Mokk to GitHub Pages"
          git push
